# -*- coding: utf-8 -*-
"""Exercicios_Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dv4uar4Z0GrZCukLXhIZt4qdqISoIQes
"""

Nota01 = float(input("Digite sua primeira nota: "))
Nota02 = float(input("Digite sua segunda nota: "))
Nota03 = float(input("Digite sua terceira nota: "))
Media = (Nota01 + Nota02 + Nota03)/3

if Media == 10:
    print("Aprovado com Distinção")
    
elif Media >= 7:
    print("Aprovado")
    
else: 
    print("Reprovado")